name: LFS download from private repo
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Checkout dataset repo
        uses: actions/checkout@v2
        with: 
          repository: ykawamura96/rlbench_data
          token: ${{ secrets.PAT }} 
          path: dataset
      - name: Unzip dataset
        run: |
          tar -zvf dataset/close_box.tar.gz
          sudo apt-get -y install tree
          tree