name: LFS download from private repo
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Checkout dataset repo
        uses: actions/checkout@v2
        with: 
          repository: ykawamura96/rlbench_data
          token: ${{ secrets.PAT }} 
          path: dataset
      - name: Unzip dataset
        run: |
          rm -rf dataset/close_box
          sudo apt-get -y install tree gzip
          tar -xvf dataset/episode0.tar.gz
          tree